//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.Forms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RentCarContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RentCarContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXApplication1.Forms.Localization.RentCarContextResources", typeof(RentCarContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Brand_CreationDate {
            get {
                return ResourceManager.GetString("Brand_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Brand_Description {
            get {
                return ResourceManager.GetString("Brand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Brand_Id {
            get {
                return ResourceManager.GetString("Brand_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string Brand_IsActive {
            get {
                return ResourceManager.GetString("Brand_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Brand_UpdateDate {
            get {
                return ResourceManager.GetString("Brand_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Model.
        /// </summary>
        public static string BrandModel {
            get {
                return ResourceManager.GetString("BrandModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BrandModel_Brand {
            get {
                return ResourceManager.GetString("BrandModel_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string BrandModel_CreationDate {
            get {
                return ResourceManager.GetString("BrandModel_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BrandModel_Description {
            get {
                return ResourceManager.GetString("BrandModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string BrandModel_Id {
            get {
                return ResourceManager.GetString("BrandModel_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string BrandModel_IsActive {
            get {
                return ResourceManager.GetString("BrandModel_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string BrandModel_UpdateDate {
            get {
                return ResourceManager.GetString("BrandModel_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Models.
        /// </summary>
        public static string BrandModelPlural {
            get {
                return ResourceManager.GetString("BrandModelPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string BrandPlural {
            get {
                return ResourceManager.GetString("BrandPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Client_CreationDate {
            get {
                return ResourceManager.GetString("Client_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Car Number.
        /// </summary>
        public static string Client_CreditCarNumber {
            get {
                return ResourceManager.GetString("Client_CreditCarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        public static string Client_CreditLimit {
            get {
                return ResourceManager.GetString("Client_CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Client_Id {
            get {
                return ResourceManager.GetString("Client_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Client_Identification {
            get {
                return ResourceManager.GetString("Client_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string Client_IsActive {
            get {
                return ResourceManager.GetString("Client_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Client_Name {
            get {
                return ResourceManager.GetString("Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Client_UpdateDate {
            get {
                return ResourceManager.GetString("Client_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ClientPlural {
            get {
                return ResourceManager.GetString("ClientPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission Date.
        /// </summary>
        public static string Employee_AdmissionDate {
            get {
                return ResourceManager.GetString("Employee_AdmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Employee_CreationDate {
            get {
                return ResourceManager.GetString("Employee_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Employee_Id {
            get {
                return ResourceManager.GetString("Employee_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Employee_Identification {
            get {
                return ResourceManager.GetString("Employee_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Type.
        /// </summary>
        public static string Employee_IdentificationType {
            get {
                return ResourceManager.GetString("Employee_IdentificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string Employee_IsActive {
            get {
                return ResourceManager.GetString("Employee_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Commission.
        /// </summary>
        public static string Employee_PercentCommission {
            get {
                return ResourceManager.GetString("Employee_PercentCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Employee_UpdateDate {
            get {
                return ResourceManager.GetString("Employee_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload.
        /// </summary>
        public static string Employee_Workload {
            get {
                return ResourceManager.GetString("Employee_Workload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeePlural {
            get {
                return ResourceManager.GetString("EmployeePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string FuelType_CreationDate {
            get {
                return ResourceManager.GetString("FuelType_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FuelType_Description {
            get {
                return ResourceManager.GetString("FuelType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FuelType_Id {
            get {
                return ResourceManager.GetString("FuelType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string FuelType_IsActive {
            get {
                return ResourceManager.GetString("FuelType_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string FuelType_UpdateDate {
            get {
                return ResourceManager.GetString("FuelType_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Types.
        /// </summary>
        public static string FuelTypePlural {
            get {
                return ResourceManager.GetString("FuelTypePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection.
        /// </summary>
        public static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Inspection_Client {
            get {
                return ResourceManager.GetString("Inspection_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Inspection_CreationDate {
            get {
                return ResourceManager.GetString("Inspection_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Quantity.
        /// </summary>
        public static string Inspection_FuelQuantity {
            get {
                return ResourceManager.GetString("Inspection_FuelQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Glass Breaks.
        /// </summary>
        public static string Inspection_HasGlassBreaks {
            get {
                return ResourceManager.GetString("Inspection_HasGlassBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Grazes.
        /// </summary>
        public static string Inspection_HasGrazes {
            get {
                return ResourceManager.GetString("Inspection_HasGrazes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Hydraulic Jack.
        /// </summary>
        public static string Inspection_HasHydraulicJack {
            get {
                return ResourceManager.GetString("Inspection_HasHydraulicJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Replacement Rubber.
        /// </summary>
        public static string Inspection_HasReplacementRubber {
            get {
                return ResourceManager.GetString("Inspection_HasReplacementRubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Inspection_Id {
            get {
                return ResourceManager.GetString("Inspection_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber Four.
        /// </summary>
        public static string Inspection_RubberFour {
            get {
                return ResourceManager.GetString("Inspection_RubberFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber One.
        /// </summary>
        public static string Inspection_RubberOne {
            get {
                return ResourceManager.GetString("Inspection_RubberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber Three.
        /// </summary>
        public static string Inspection_RubberThree {
            get {
                return ResourceManager.GetString("Inspection_RubberThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber Two.
        /// </summary>
        public static string Inspection_RubberTwo {
            get {
                return ResourceManager.GetString("Inspection_RubberTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Inspection_UpdateDate {
            get {
                return ResourceManager.GetString("Inspection_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Inspection_Vehicle {
            get {
                return ResourceManager.GetString("Inspection_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspections.
        /// </summary>
        public static string InspectionPlural {
            get {
                return ResourceManager.GetString("InspectionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Per Day.
        /// </summary>
        public static string Rent_AmountPerDay {
            get {
                return ResourceManager.GetString("Rent_AmountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Rent_Client {
            get {
                return ResourceManager.GetString("Rent_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Rent_Comment {
            get {
                return ResourceManager.GetString("Rent_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Rent_CreationDate {
            get {
                return ResourceManager.GetString("Rent_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Quantity.
        /// </summary>
        public static string Rent_DayQuantity {
            get {
                return ResourceManager.GetString("Rent_DayQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Rent_Employee {
            get {
                return ResourceManager.GetString("Rent_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Rent_Id {
            get {
                return ResourceManager.GetString("Rent_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string Rent_IsActive {
            get {
                return ResourceManager.GetString("Rent_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Date.
        /// </summary>
        public static string Rent_RentDate {
            get {
                return ResourceManager.GetString("Rent_RentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        public static string Rent_ReturnDate {
            get {
                return ResourceManager.GetString("Rent_ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Rent_UpdateDate {
            get {
                return ResourceManager.GetString("Rent_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Rent_Vehicle {
            get {
                return ResourceManager.GetString("Rent_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rents.
        /// </summary>
        public static string RentPlural {
            get {
                return ResourceManager.GetString("RentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Vehicle_Brand {
            get {
                return ResourceManager.GetString("Vehicle_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Model.
        /// </summary>
        public static string Vehicle_BrandModel {
            get {
                return ResourceManager.GetString("Vehicle_BrandModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Number.
        /// </summary>
        public static string Vehicle_ChassisNumber {
            get {
                return ResourceManager.GetString("Vehicle_ChassisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string Vehicle_CreationDate {
            get {
                return ResourceManager.GetString("Vehicle_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Vehicle_Description {
            get {
                return ResourceManager.GetString("Vehicle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string Vehicle_FuelType {
            get {
                return ResourceManager.GetString("Vehicle_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Vehicle_Id {
            get {
                return ResourceManager.GetString("Vehicle_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string Vehicle_IsActive {
            get {
                return ResourceManager.GetString("Vehicle_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string Vehicle_LicensePlate {
            get {
                return ResourceManager.GetString("Vehicle_LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Number.
        /// </summary>
        public static string Vehicle_MotorNumber {
            get {
                return ResourceManager.GetString("Vehicle_MotorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Vehicle_UpdateDate {
            get {
                return ResourceManager.GetString("Vehicle_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string Vehicle_VehicleType {
            get {
                return ResourceManager.GetString("Vehicle_VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string VehiclePlural {
            get {
                return ResourceManager.GetString("VehiclePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string VehicleType_CreationDate {
            get {
                return ResourceManager.GetString("VehicleType_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string VehicleType_Description {
            get {
                return ResourceManager.GetString("VehicleType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string VehicleType_Id {
            get {
                return ResourceManager.GetString("VehicleType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string VehicleType_IsActive {
            get {
                return ResourceManager.GetString("VehicleType_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string VehicleType_UpdateDate {
            get {
                return ResourceManager.GetString("VehicleType_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Types.
        /// </summary>
        public static string VehicleTypePlural {
            get {
                return ResourceManager.GetString("VehicleTypePlural", resourceCulture);
            }
        }
    }
}
