//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1.Forms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RentCarContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RentCarContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXApplication1.Forms.Localization.RentCarContextResources", typeof(RentCarContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Brand_Description {
            get {
                return ResourceManager.GetString("Brand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Brand_Id {
            get {
                return ResourceManager.GetString("Brand_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Brand_Status {
            get {
                return ResourceManager.GetString("Brand_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string BrandPlural {
            get {
                return ResourceManager.GetString("BrandPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr Card.
        /// </summary>
        public static string Client_CrCard {
            get {
                return ResourceManager.GetString("Client_CrCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        public static string Client_CreditLimit {
            get {
                return ResourceManager.GetString("Client_CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Client_Id {
            get {
                return ResourceManager.GetString("Client_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Client_Identification {
            get {
                return ResourceManager.GetString("Client_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Client_Name {
            get {
                return ResourceManager.GetString("Client_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Type.
        /// </summary>
        public static string Client_PersonType {
            get {
                return ResourceManager.GetString("Client_PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Client_Status {
            get {
                return ResourceManager.GetString("Client_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ClientPlural {
            get {
                return ResourceManager.GetString("ClientPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission Date.
        /// </summary>
        public static string Employee_AdmissionDate {
            get {
                return ResourceManager.GetString("Employee_AdmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Employee_Id {
            get {
                return ResourceManager.GetString("Employee_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Employee_Identification {
            get {
                return ResourceManager.GetString("Employee_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Commission.
        /// </summary>
        public static string Employee_PercentCommission {
            get {
                return ResourceManager.GetString("Employee_PercentCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Employee_Status {
            get {
                return ResourceManager.GetString("Employee_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shift.
        /// </summary>
        public static string Employee_WorkShift {
            get {
                return ResourceManager.GetString("Employee_WorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeePlural {
            get {
                return ResourceManager.GetString("EmployeePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string FuelType_Description {
            get {
                return ResourceManager.GetString("FuelType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FuelType_Id {
            get {
                return ResourceManager.GetString("FuelType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FuelType_Status {
            get {
                return ResourceManager.GetString("FuelType_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Types.
        /// </summary>
        public static string FuelTypePlural {
            get {
                return ResourceManager.GetString("FuelTypePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection.
        /// </summary>
        public static string Inspection {
            get {
                return ResourceManager.GetString("Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Inspection_Client {
            get {
                return ResourceManager.GetString("Inspection_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Inspection_Date {
            get {
                return ResourceManager.GetString("Inspection_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Inspection_Employee {
            get {
                return ResourceManager.GetString("Inspection_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Amount.
        /// </summary>
        public static string Inspection_FuelAmount {
            get {
                return ResourceManager.GetString("Inspection_FuelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has ACat.
        /// </summary>
        public static string Inspection_HasACat {
            get {
                return ResourceManager.GetString("Inspection_HasACat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Carvings.
        /// </summary>
        public static string Inspection_HasCarvings {
            get {
                return ResourceManager.GetString("Inspection_HasCarvings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Glass Breaks.
        /// </summary>
        public static string Inspection_HasGlassBreaks {
            get {
                return ResourceManager.GetString("Inspection_HasGlassBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Spare Rubber.
        /// </summary>
        public static string Inspection_HasSpareRubber {
            get {
                return ResourceManager.GetString("Inspection_HasSpareRubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Inspection_Id {
            get {
                return ResourceManager.GetString("Inspection_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State First Rubber.
        /// </summary>
        public static string Inspection_StateFirstRubber {
            get {
                return ResourceManager.GetString("Inspection_StateFirstRubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Fourth Rubber.
        /// </summary>
        public static string Inspection_StateFourthRubber {
            get {
                return ResourceManager.GetString("Inspection_StateFourthRubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Second Rubber.
        /// </summary>
        public static string Inspection_StateSecondRubber {
            get {
                return ResourceManager.GetString("Inspection_StateSecondRubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Third Rubber.
        /// </summary>
        public static string Inspection_StateThirdRubber {
            get {
                return ResourceManager.GetString("Inspection_StateThirdRubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Inspection_Status {
            get {
                return ResourceManager.GetString("Inspection_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Inspection_Vehicle {
            get {
                return ResourceManager.GetString("Inspection_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspections.
        /// </summary>
        public static string InspectionPlural {
            get {
                return ResourceManager.GetString("InspectionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Model_Brand {
            get {
                return ResourceManager.GetString("Model_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Model_Description {
            get {
                return ResourceManager.GetString("Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Model_Id {
            get {
                return ResourceManager.GetString("Model_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Model_Status {
            get {
                return ResourceManager.GetString("Model_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string ModelPlural {
            get {
                return ResourceManager.GetString("ModelPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Per Day.
        /// </summary>
        public static string Rent_AmountPerDay {
            get {
                return ResourceManager.GetString("Rent_AmountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Rent_Client {
            get {
                return ResourceManager.GetString("Rent_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Rent_Comment {
            get {
                return ResourceManager.GetString("Rent_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Quantity.
        /// </summary>
        public static string Rent_DaysQuantity {
            get {
                return ResourceManager.GetString("Rent_DaysQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Rent_Employee {
            get {
                return ResourceManager.GetString("Rent_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Rent_Id {
            get {
                return ResourceManager.GetString("Rent_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Date Time.
        /// </summary>
        public static string Rent_RentDateTime {
            get {
                return ResourceManager.GetString("Rent_RentDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date Time.
        /// </summary>
        public static string Rent_ReturnDateTime {
            get {
                return ResourceManager.GetString("Rent_ReturnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Rent_Status {
            get {
                return ResourceManager.GetString("Rent_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Rent_Vehicle {
            get {
                return ResourceManager.GetString("Rent_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rents.
        /// </summary>
        public static string RentPlural {
            get {
                return ResourceManager.GetString("RentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Vehicle_Brand {
            get {
                return ResourceManager.GetString("Vehicle_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Number.
        /// </summary>
        public static string Vehicle_ChassisNumber {
            get {
                return ResourceManager.GetString("Vehicle_ChassisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Vehicle_Description {
            get {
                return ResourceManager.GetString("Vehicle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string Vehicle_FuelType {
            get {
                return ResourceManager.GetString("Vehicle_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Vehicle_Id {
            get {
                return ResourceManager.GetString("Vehicle_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Vehicle_Model {
            get {
                return ResourceManager.GetString("Vehicle_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Number.
        /// </summary>
        public static string Vehicle_MotorNumber {
            get {
                return ResourceManager.GetString("Vehicle_MotorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        public static string Vehicle_PlateNumber {
            get {
                return ResourceManager.GetString("Vehicle_PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Vehicle_Status {
            get {
                return ResourceManager.GetString("Vehicle_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string Vehicle_VehicleType {
            get {
                return ResourceManager.GetString("Vehicle_VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string VehiclePlural {
            get {
                return ResourceManager.GetString("VehiclePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string VehicleType_Description {
            get {
                return ResourceManager.GetString("VehicleType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string VehicleType_Id {
            get {
                return ResourceManager.GetString("VehicleType_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VehicleType_Status {
            get {
                return ResourceManager.GetString("VehicleType_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Types.
        /// </summary>
        public static string VehicleTypePlural {
            get {
                return ResourceManager.GetString("VehicleTypePlural", resourceCulture);
            }
        }
    }
}
